/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import dao.IUserDao;
import pojo.UserInfo;
import struts.form.RegisterForm;


public class RegisterAction extends DispatchAction {
	private IUserDao userDao;
	public IUserDao getUserDao() {
		return userDao;
	}
	public void setUserDao(IUserDao userDao) {
		this.userDao = userDao;
	}
	public ActionForward register(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;
		UserInfo userInfo = new UserInfo();
		userInfo.setAge(registerForm.getAge());
		userInfo.setUserName(registerForm.getUserName());
		try {
			this.getUserDao().save(userInfo);
		} catch (Exception e) {
			return mapping.findForward("error");
		}
		return mapping.findForward("ok");
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;
		UserInfo userInfo = null; 
		List list = null;
		try {
			userInfo = this.userDao.queryByName(registerForm.getUserName());
			list = this.userDao.queryAllUser();
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (userInfo != null) {
			request.setAttribute("list",list);
			return mapping.findForward("main");
		} else {
			return mapping.findForward("index");
		}
	}
}